### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by Jeoyal** [uozyurt/MasterMetaStyleTransfer#15]
Could you provide the pretrained weights of your models?

**Comment by uozyurt** [comment]
@Jeoyal Hi!

We've placed our pretrained weights in the test/pretrained_weights folder.

**Comment by uozyurt** [comment]
@Jeoyal Hi!

We've placed our pretrained weights in the test/pretrained_weights folder.

**Comment by Jeoyal** [comment]
@uozyurt thank you for your quick reply. I noticed that you have implement layer 1, 3, 5, which layer could be consider as the final stylized output?

**Comment by uozyurt** [comment]
The layer count is optional. Same layer is used any number of times. The larger it is, the more stylized the output is expected. You choose the layer number in forward pass as you wish.

**Comment by Jeoyal** [comment]
I have read the Style loss and Content loss in your main.ipynb, it seems like layer 5 is best?

**Comment by uozyurt** [comment]
Layer 5 means passing the input to the layer 5 times. And the layer is "Style Transformer Layer" in the paper.

More directly, 5 or 3 in "layer 5" or "layer 3" correspondes to the $N_{layer}$ term in the figure below. (Which means it is optional. It changes from person to person regarding how much they want to sylize the image.)

![image](https://github.com/user-attachments/assets/5e9799d9-f6d5-45bf-9a3d-bd4eaa36edd9)

**Comment by Jeoyal** [comment]
I see! Thank you!!
